default: &default
  appid: 'xxxxx'
  secret: 'xxxxx'
  token: 'xxxxx'
  access_token: <%= File.expand_path('../tmp/sockets/wechat_access_token', __FILE__) %>
  jsapi_ticket: <%= File.expand_path('../tmp/sockets/wechat_jsapi_ticket', __FILE__) %>

production:
  <<: *default

development:
  <<: *default
  trusted_domain_fullname: 'http://wx.bestpv.cn'

test:
  <<: *default
# Multiple Accounts
#
# wx2_development:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#  access_token: "tmp/wechat_access_token2"
#  jsapi_ticket: "tmp/wechat_jsapi_ticket2"
#
# wx2_test:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
# wx2_production:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
# wx3_development:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#  access_token: "tmp/wechat_access_token3"
#  jsapi_ticket: "tmp/wechat_jsapi_ticket3"
#
# wx3_test:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
# wx3_production:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
